### PR TITLE
@ #28 | shoult add MIT license file

### PR DESCRIPTION
**Pull request by hieptranquoc**
connect #28

### CODE REVIEW

**Comment by hieptranquoc** [comment]
@hoatle check this PR , plz and release!

**Comment by hoatle** [comment]
@hieptranquoc you forgot this requirement from the issue "update on README"

**Review by hoatle — CHANGES_REQUESTED** [review]
need to update README

**Comment by hieptranquoc** [comment]
@hoatle updated License section on the README file!

**Review by hoatle — APPROVED** [review]
LGTM

**Pull request merged**
